name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build (Linux)
      run: cargo build --release --verbose
    
    - name: Build (Windows)
      run: cargo build --release --verbose --target x86_64-pc-windows-gnu
    
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
    - name: Download built binaries
      uses: actions/download-artifact@v5
      with:
        name: target
  
    - name: Move binaries
      run: |
        mkdir binaries
        mv x86_64-pc-windows-gnu/release/poong.exe binaries/poong-${{ github.event.release.tag_name }}-x86_64-windows.exe
        mv release/poong binaries/poong-${{ github.event.release.tag_name }}-x86_64-linux
    
    - name: Publish a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: binaries
